blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/ccook7bit/VSP_Calibration_Pipeline/discussions
    about: For questions, please open a discussion thread instead of an issue.
